# Generated by Django 4.2.20 on 2025-03-23 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Analysis Completed'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('real', 'Real'), ('fake', 'Fake'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('sequence_length', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Video',
                'verbose_name_plural': 'Uploaded Videos',
                'ordering': ['-upload_time'],
            },
        ),
    ]
