# Generated by Django 4.2.20 on 2025-03-23 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('real', 'Real'), ('fake', 'Fake'), ('unknown', 'Unknown')], max_length=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('frames_analyzed', models.IntegerField(default=0)),
                ('detection_time', models.FloatField(default=0.0, help_text='Time taken for detection in seconds')),
                ('video_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.DeleteModel(
            name='UploadedVideo',
        ),
    ]
